
ALTER TABLE `CodeforcesTags` ADD `importance` FLOAT NULL DEFAULT '0' AFTER `russianName`;
UPDATE `CodeforcesTags` SET `importance` = 0.617422 WHERE `CodeforcesTags`.`id` = 1;
UPDATE `CodeforcesTags` SET `importance` = 0.904154 WHERE `CodeforcesTags`.`id` = 2;
UPDATE `CodeforcesTags` SET `importance` = 0.792531 WHERE `CodeforcesTags`.`id` = 3;
UPDATE `CodeforcesTags` SET `importance` = 0.563012 WHERE `CodeforcesTags`.`id` = 4;
UPDATE `CodeforcesTags` SET `importance` = 0.907213 WHERE `CodeforcesTags`.`id` = 5;
UPDATE `CodeforcesTags` SET `importance` = 0.895877 WHERE `CodeforcesTags`.`id` = 6;
UPDATE `CodeforcesTags` SET `importance` = 0.41226 WHERE `CodeforcesTags`.`id` = 7;
UPDATE `CodeforcesTags` SET `importance` = 0.690597 WHERE `CodeforcesTags`.`id` = 8;
UPDATE `CodeforcesTags` SET `importance` = 0.804048 WHERE `CodeforcesTags`.`id` = 9;
UPDATE `CodeforcesTags` SET `importance` = 0.698986 WHERE `CodeforcesTags`.`id` = 10;
UPDATE `CodeforcesTags` SET `importance` = 0.859861 WHERE `CodeforcesTags`.`id` = 11;
UPDATE `CodeforcesTags` SET `importance` = 0.728052 WHERE `CodeforcesTags`.`id` = 12;
UPDATE `CodeforcesTags` SET `importance` = 0.755274 WHERE `CodeforcesTags`.`id` = 13;
UPDATE `CodeforcesTags` SET `importance` = 0.83712 WHERE `CodeforcesTags`.`id` = 14;
UPDATE `CodeforcesTags` SET `importance` = 0.703059 WHERE `CodeforcesTags`.`id` = 15;
UPDATE `CodeforcesTags` SET `importance` = 0.783768 WHERE `CodeforcesTags`.`id` = 16;
UPDATE `CodeforcesTags` SET `importance` = 0.475527 WHERE `CodeforcesTags`.`id` = 17;
UPDATE `CodeforcesTags` SET `importance` = 0.978693 WHERE `CodeforcesTags`.`id` = 18;
UPDATE `CodeforcesTags` SET `importance` = 0.592865 WHERE `CodeforcesTags`.`id` = 19;
UPDATE `CodeforcesTags` SET `importance` = 1 WHERE `CodeforcesTags`.`id` = 20;
UPDATE `CodeforcesTags` SET `importance` = 0.540804 WHERE `CodeforcesTags`.`id` = 21;
UPDATE `CodeforcesTags` SET `importance` = 0.93146 WHERE `CodeforcesTags`.`id` = 22;
UPDATE `CodeforcesTags` SET `importance` = 0.1 WHERE `CodeforcesTags`.`id` = 23;
UPDATE `CodeforcesTags` SET `importance` = 0.81815 WHERE `CodeforcesTags`.`id` = 24;
UPDATE `CodeforcesTags` SET `importance` = 0.851402 WHERE `CodeforcesTags`.`id` = 25;
UPDATE `CodeforcesTags` SET `importance` = 0.99105 WHERE `CodeforcesTags`.`id` = 26;
UPDATE `CodeforcesTags` SET `importance` = 0.516718 WHERE `CodeforcesTags`.`id` = 27;
UPDATE `CodeforcesTags` SET `importance` = 0.274297 WHERE `CodeforcesTags`.`id` = 28;
UPDATE `CodeforcesTags` SET `importance` = 0.857776 WHERE `CodeforcesTags`.`id` = 29;
UPDATE `CodeforcesTags` SET `importance` = 0.599735 WHERE `CodeforcesTags`.`id` = 30;
UPDATE `CodeforcesTags` SET `importance` = 0.500077 WHERE `CodeforcesTags`.`id` = 31;
UPDATE `CodeforcesTags` SET `importance` = 0.48602 WHERE `CodeforcesTags`.`id` = 32;
UPDATE `CodeforcesTags` SET `importance` = 0.675242 WHERE `CodeforcesTags`.`id` = 33;
UPDATE `CodeforcesTags` SET `importance` = 0.756745 WHERE `CodeforcesTags`.`id` = 34;
UPDATE `CodeforcesTags` SET `importance` = 0.7688 WHERE `CodeforcesTags`.`id` = 35;
UPDATE `CodeforcesTags` SET `importance` = 0.682311 WHERE `CodeforcesTags`.`id` = 36;
UPDATE `CodeforcesTags` SET `importance` = 0 WHERE `CodeforcesTags`.`id` = 37;
UPDATE `CodeforcesTags` SET `importance` = 0 WHERE `CodeforcesTags`.`id` = 38;
UPDATE `CodeforcesTags` SET `importance` = 0 WHERE `CodeforcesTags`.`id` = 39;
UPDATE `CodeforcesTags` SET `importance` = 0 WHERE `CodeforcesTags`.`id` = 40;
UPDATE `CodeforcesTags` SET `importance` = 0 WHERE `CodeforcesTags`.`id` = 41;
UPDATE `CodeforcesTags` SET `importance` = 0 WHERE `CodeforcesTags`.`id` = 42;
UPDATE `CodeforcesTags` SET `importance` = 0 WHERE `CodeforcesTags`.`id` = 43;


